### ISSUE TITLE
enhance form

### ISSUE THREAD

**Issue by VANSHAJB10** [VANSHAJB10/ContactForm#1]
Update the form code so that on clicking the 'Submit' button 2 actions happen :
1. The form data is sent to email: for now, take the sample email id as 'help@sc.com'
2. A pop-up/message appears: "Your form is submitted. Please  <a href="#">click here</a>  to proceed to the final step of registration".

If you are implementing a pop-up, make sure the background is #ffffff. and the font family is Poppins.
If you are implementing a message, the message should appear below the 'Submit' button with the text of color #0f0f0f.

IMPORTANT!!
If the above conditions are not fulfilled, your PR will not be accepted.

**Comment by VANSHAJB10** [comment]
Javascript is not working correctly after your proposed changes:
Each input box heading is not moving to the top as soon as clicked inside the box for typing in. 

Refer to the attached photo:👇
![Untitled design (2)](https://github.com/VANSHAJB10/ContactForm/assets/95224854/83301a02-cd95-4c32-ba8d-9fe2f0217eea)

**Comment by chris-fink** [comment]
I see the issue now. The handleSubmit needed to be a function. PR updated to reflect functionality.
